#!/usr/bin/env bash
#
# quickstart.sh — get all three bots running in minutes.
#
# What it does:
#   1. Creates a Python virtualenv and installs dependencies.
#   2. Asks for your 3 bot tokens + admin ID(s) + default mint (once), saves
#      them to .env (chmod 600).
#   3. Launches Guardian + Scanner + Community together. Ctrl-C stops all three.
#
# Re-run any time — it reuses the venv and your saved .env.
#
# Usage:
#   bash quickstart.sh            # set up + run all three (foreground)
#   bash quickstart.sh --setup    # set up + write .env only, don't launch
#
set -euo pipefail
cd "$(dirname "$0")"

PY="${PYTHON:-python3}"
VENV="venv"
ENV_FILE=".env"

echo "==> Degen bot fleet quickstart"

# --- 1. Python + venv ------------------------------------------------------- #
if ! command -v "$PY" >/dev/null 2>&1; then
  echo "ERROR: $PY not found. Install Python 3.10+ first:" >&2
  echo "  sudo apt update && sudo apt install -y python3 python3-pip python3-venv" >&2
  exit 1
fi

if [ ! -d "$VENV" ]; then
  echo "==> Creating virtualenv ($VENV)…"
  "$PY" -m venv "$VENV"
fi
# shellcheck disable=SC1091
source "$VENV/bin/activate"

echo "==> Installing dependencies…"
pip install --quiet --upgrade pip
pip install --quiet -r requirements.txt
echo "    done."

# --- 2. .env --------------------------------------------------------------- #
prompt_secret() {  # $1 var name, $2 human label
  local val=""
  while [ -z "$val" ]; do
    read -r -p "    $2: " val
    [ -z "$val" ] && echo "    (required)"
  done
  printf '%s' "$val"
}

if [ -f "$ENV_FILE" ]; then
  # shellcheck disable=SC1090
  set -a; source "$ENV_FILE"; set +a
fi

if [ -z "${TG_BOT_TOKEN:-}" ] || [ -z "${TG_SCANNER_TOKEN:-}" ] || \
   [ -z "${TG_COMMUNITY_TOKEN:-}" ] || [ -z "${TG_ADMIN_IDS:-}" ]; then
  echo
  echo "==> Let's fill in your secrets (saved to $ENV_FILE, never committed)."
  echo "    Get tokens from @BotFather (/newbot), your numeric ID from @userinfobot."
  echo
  TG_ADMIN_IDS="$(prompt_secret TG_ADMIN_IDS 'Admin numeric ID(s), comma-separated (e.g. 11122233)')"
  TG_BOT_TOKEN="$(prompt_secret TG_BOT_TOKEN 'GUARDIAN bot token')"
  TG_SCANNER_TOKEN="$(prompt_secret TG_SCANNER_TOKEN 'SCANNER bot token')"
  TG_COMMUNITY_TOKEN="$(prompt_secret TG_COMMUNITY_TOKEN 'COMMUNITY bot token')"
  read -r -p "    Default token mint (optional, for /price — Enter to skip): " DEFAULT_TOKEN_MINT || true

  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by quickstart.sh — keep secret, never commit.
TG_ADMIN_IDS=$TG_ADMIN_IDS
TG_BOT_TOKEN=$TG_BOT_TOKEN
TG_SCANNER_TOKEN=$TG_SCANNER_TOKEN
TG_COMMUNITY_TOKEN=$TG_COMMUNITY_TOKEN
DEFAULT_TOKEN_MINT=${DEFAULT_TOKEN_MINT:-}
EOF
  chmod 600 "$ENV_FILE"
  echo "    saved $ENV_FILE (chmod 600)."
  # shellcheck disable=SC1090
  set -a; source "$ENV_FILE"; set +a
fi

if [ "${1:-}" = "--setup" ]; then
  echo "==> Setup complete. Run 'bash quickstart.sh' to launch the bots."
  exit 0
fi

# --- 3. Launch all three --------------------------------------------------- #
echo
echo "==> Launching Guardian + Scanner + Community. Press Ctrl-C to stop all."
echo

pids=()
cleanup() { echo; echo "==> Stopping…"; for p in "${pids[@]}"; do kill "$p" 2>/dev/null || true; done; }
trap cleanup INT TERM EXIT

python guardian_bot.py        & pids+=($!)
python solana_scanner_bot.py  & pids+=($!)
python community_bot.py       & pids+=($!)

wait
